FROM fedora:latest
RUN dnf install -y appstream automake boost-devel curl file gcc gcc-c++ gettext-devel gmp-devel gnutls-devel libargon2-devel libtool make meson nettle-devel ninja-build patch pugixml-devel sqlite-devel wxGTK-devel xdg-utils

RUN \
	cd /opt && \
	curl -L -o ./appimagetool-x86_64.AppImage https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage && \
	chmod +x ./appimagetool-x86_64.AppImage && \
	exit 0

ENV CFLAGS="-O3 -march=native -flto"
ENV CXXFLAGS="-O3 -march=native -flto"
ENV LDFLAGS="-flto"
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

ADD ./libfilezilla /opt/libfilezilla
RUN \
	cd /opt/libfilezilla && \
	autoreconf -f -i && \
	./configure && \
	make -j$(nproc) && \
	make install && \
	exit 0

ADD ./fzssh /opt/fzssh
RUN \
	cd /opt/fzssh && \
	meson setup --libdir=lib build && \
	cd build && \
	meson install && \
	exit 0

ADD ./filezilla /opt/filezilla
ADD ./transfer-limits.patch /opt/transfer-limits.patch
RUN \
	cd /opt && \
	patch -p1 < /opt/transfer-limits.patch && \
	cd /opt/filezilla && \
	autoreconf -f -i && \
	./configure && \
	make -j$(nproc) && \
	make install && \
	exit 0

ADD ./AppRun.sh /opt/approot/AppRun
ADD ./filezilla.desktop /opt/approot
RUN \
	mkdir -p /opt/approot/opt/filezilla && \
	cp /usr/local/bin/filezilla /opt/approot/opt/filezilla && \
	cp /opt/filezilla/src/interface/resources/480x480/filezilla.png /opt/approot/filezilla.png && \
	cp -P /usr/local/lib/libf* /opt/approot/opt/filezilla && \
	cp -P /lib64/libcrypt.so* /opt/approot/opt/filezilla && \
	cp -P /lib64/libpugixml.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib64/libwx_*.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib64/libjpeg.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib64/libmspack.so* /opt/approot/opt/filezilla && \
	cp -r /usr/local/share/filezilla /opt/approot/opt/filezilla/share && \
	strip -s /opt/approot/opt/filezilla/filezilla && \
	strip -s /opt/approot/opt/filezilla/*.so* && \
	chmod +x /opt/approot/AppRun && \
	exit 0

ENTRYPOINT ["/opt/appimagetool-x86_64.AppImage", "--comp", "zstd", "/opt/approot", "/opt/FileZilla.AppImage"]
