FROM ubuntu:latest
RUN apt-get update && apt-get install -yq automake curl file g++ gcc gettext libboost-all-dev libdbus-1-dev libgmp-dev libgnutls28-dev libgtk-3-dev libpugixml-dev libsqlite3-dev libtool libwxgtk3.2-dev make nettle-dev patch pkg-config xdg-utils

RUN \
	cd /opt && \
	curl -L -o ./appimagetool-x86_64.AppImage https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage && \
	chmod +x ./appimagetool-x86_64.AppImage && \
	exit 0

ENV CFLAGS="-O3 -march=native"
ENV CXXFLAGS="-O3 -march=native"

ADD ./libfilezilla /opt/libfilezilla
RUN \
	cd /opt/libfilezilla && \
	autoreconf -f -i && \
	./configure && \
	make -j$(nproc) && \
	make install && \
	exit 0

ADD ./filezilla /opt/filezilla
ADD ./transfer-limits.patch /opt/transfer-limits.patch
RUN \
	cd /opt && \
	patch -p1 < /opt/transfer-limits.patch && \
	cd /opt/filezilla && \
	mkdir -p ./src/fzshellext/32 && \
	mkdir -p ./src/fzshellext/64 && \
	autoreconf -f -i && \
	PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure && \
	make -j$(nproc) && \
	make install && \
	exit 0

ADD ./AppRun.sh /opt/approot/AppRun
ADD ./filezilla.desktop /opt/approot
RUN \
	mkdir -p /opt/approot/opt/filezilla && \
	cp /opt/filezilla/src/interface/resources/480x480/filezilla.png /opt/approot/opt/filezilla/icon.png && \
	cp -P /usr/local/lib/libf* /opt/approot/opt/filezilla && \
	cp -P /lib/x86_64-linux-gnu/libcrypt.so* /opt/approot/opt/filezilla && \
	cp -P /lib/x86_64-linux-gnu/libpugixml.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libwx_*.so* /opt/approot/opt/filezilla && \
	cp -r /usr/local/share/filezilla /opt/approot/opt/filezilla/share && \
	cp /usr/local/bin/filezilla /opt/approot/opt/filezilla && \
	cp /usr/local/bin/fzsftp /opt/approot/opt/filezilla && \
	cp /usr/local/bin/fzputtygen /opt/approot/opt/filezilla && \
	strip -s /opt/approot/opt/filezilla/filezilla && \
	strip -s /opt/approot/opt/filezilla/*.so && \
	chmod +x /opt/approot/AppRun && \
	exit 0

ENTRYPOINT ["/opt/appimagetool-x86_64.AppImage", "/opt/approot", "/opt/FileZilla.AppImage"]
