FROM ubuntu:24.04
RUN apt-get update && apt-get install -yq appstream automake g++ gcc gettext libargon2-dev libboost-regex-dev libdbus-1-dev libgmp-dev libgnutls28-dev libgtk-3-dev libpugixml-dev libsqlite3-dev libtool libwxgtk3.2-dev make meson ninja-build patch pkg-config xdg-utils

ADD https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage /opt/appimagetool-x86_64.AppImage
RUN chmod +x /opt/appimagetool-x86_64.AppImage

ENV CFLAGS="-O3 -march=native -flto"
ENV CXXFLAGS="-O3 -march=native -flto"
ENV LDFLAGS="-flto"
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

ADD https://ftp.gnu.org/gnu/nettle/nettle-3.10.2.tar.gz /opt/nettle.tar.gz
RUN \
	cd /opt && \
	tar -xf /opt/nettle.tar.gz && \
	cd /opt/nettle-3.10.2 && \
	./configure --libdir=/usr/local/lib && \
	make -j$(nproc) && \
	make install && \
	ldconfig && \
	exit 0

ADD ./libfilezilla /opt/libfilezilla
RUN \
	cd /opt/libfilezilla && \
	autoreconf -f -i && \
	./configure && \
	make -j$(nproc) && \
	make install && \
	exit 0

ADD ./fzssh /opt/fzssh
RUN \
	cd /opt/fzssh && \
	meson setup --libdir=lib build && \
	cd build && \
	meson install && \
	exit 0

ADD ./filezilla /opt/filezilla
ADD ./transfer-limits.patch /opt/transfer-limits.patch
RUN \
	cd /opt && \
	patch -p1 < /opt/transfer-limits.patch && \
	cd /opt/filezilla && \
	mkdir -p ./src/fzshellext/32 && \
	mkdir -p ./src/fzshellext/64 && \
	autoreconf -f -i && \
	./configure && \
	make -j$(nproc) && \
	make install && \
	exit 0

ADD ./AppRun.sh /opt/approot/AppRun
RUN \
	mkdir -p /opt/approot/opt/filezilla && \
	cp /usr/local/bin/filezilla /opt/approot/opt/filezilla && \
	cp /opt/filezilla/data/filezilla.desktop /opt/approot/filezilla.desktop && \
	cp /opt/filezilla/src/interface/resources/480x480/filezilla.png /opt/approot/filezilla.png && \
	cp -P /usr/local/lib/libf* /opt/approot/opt/filezilla && \
	cp -P /lib/x86_64-linux-gnu/libcrypt.so* /opt/approot/opt/filezilla && \
	cp -P /lib/x86_64-linux-gnu/libpugixml.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libwx_*.so* /opt/approot/opt/filezilla && \
	cp -r /usr/local/share/filezilla /opt/approot/opt/filezilla/share && \
	strip -s /opt/approot/opt/filezilla/filezilla && \
	strip -s /opt/approot/opt/filezilla/*.so* && \
	chmod +x /opt/approot/AppRun && \
	exit 0

ENTRYPOINT ["/opt/appimagetool-x86_64.AppImage", "--comp", "zstd", "/opt/approot", "/opt/FileZilla.AppImage"]
