FROM ubuntu:24.04
RUN apt-get update && apt-get install -yq appstream automake g++ gcc gettext libargon2-dev libboost-regex-dev libdbus-1-dev libgmp-dev libgnutls28-dev libgtk-3-dev libpugixml-dev libssl-dev libsqlite3-dev libtool libunbound-dev libwxgtk3.2-dev make meson ninja-build patch pkg-config xdg-utils && rm -rf /var/lib/apt/lists/*

ADD https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage /opt/appimagetool-x86_64.AppImage
RUN chmod +x /opt/appimagetool-x86_64.AppImage

ENV CFLAGS="-O3 -march=native -Wno-error -flto -static"
ENV CXXFLAGS="-O3 -march=native -Wno-error -flto -static"
ENV LDFLAGS="-flto -static"
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
WORKDIR /opt

ADD https://ftp.gnu.org/gnu/nettle/nettle-3.10.2.tar.gz /opt/nettle.tar.gz
RUN \
	tar -xf nettle.tar.gz && \
	cd nettle-3.10.2 && \
	./configure --libdir=/usr/local/lib --enable-static --disable-shared && \
	make -j$(nproc) && \
	make install

ADD ./libfilezilla /opt/libfilezilla
RUN \
	cd libfilezilla && \
	autoreconf -f -i && \
	./configure && \
	make -j$(nproc) && \
	make install

ADD ./fzssh /opt/fzssh
RUN \
	cd fzssh && \
	sed -i 's/shared_library(/library(/g' meson.build && \
	sed -i '/^executable(/,/^)$/d' meson.build && \
	sed -i "/^subdir('tests')/d" meson.build && \
	meson setup --libdir=lib --default-library=static build && \
	cd build && \
	meson install

ADD ./filezilla /opt/filezilla
ADD ./transfer-limits.patch /opt/transfer-limits.patch
RUN \
	patch -p1 < /opt/transfer-limits.patch && \
	cd filezilla && \
	mkdir -p ./src/fzshellext/32 ./src/fzshellext/64 && \
	autoreconf -f -i && \
	./configure --disable-manualupdatecheck --enable-static --disable-shared && \
	make -j$(nproc) && \
	make install

ADD ./AppRun.sh /opt/approot/AppRun
RUN \
	mkdir -p /opt/approot/opt/filezilla /opt/approot/usr/share/applications /opt/approot/usr/share/icons/hicolor/scalable/apps && \
	cp /usr/local/bin/filezilla /opt/approot/opt/filezilla && \
	cp /opt/filezilla/data/filezilla.desktop /opt/approot/filezilla.desktop && \
	cp /opt/filezilla/data/filezilla.desktop /opt/approot/usr/share/applications/filezilla.desktop && \
	cp /opt/filezilla/src/interface/resources/480x480/filezilla.png /opt/approot/filezilla.png && \
	for s in 16x16 32x32 48x48; do \
		mkdir -p "/opt/approot/usr/share/icons/hicolor/$s/apps" && \
		cp "/opt/filezilla/src/interface/resources/$s/filezilla.png" "/opt/approot/usr/share/icons/hicolor/$s/apps/filezilla.png"; \
	done && \
	cp /opt/filezilla/src/interface/resources/filezilla.svg /opt/approot/usr/share/icons/hicolor/scalable/apps/filezilla.svg && \
	cp -r /usr/local/share/filezilla /opt/approot/opt/filezilla/share && \
	cp -P /lib/x86_64-linux-gnu/libpugixml.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libwx_*.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libjpeg.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libtiff.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libjbig.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libwebp.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libsharpyuv.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libdeflate.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libLerc.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libpcre2-32.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib/x86_64-linux-gnu/libnotify.so* /opt/approot/opt/filezilla && \
	strip -s /opt/approot/opt/filezilla/filezilla && \
	strip -s /opt/approot/opt/filezilla/*.so* && \
	chmod +x /opt/approot/AppRun

ENTRYPOINT ["/opt/appimagetool-x86_64.AppImage", "--comp", "zstd", "/opt/approot", "/opt/FileZilla.AppImage"]
