FROM fedora:41
RUN dnf install -y appstream automake boost-devel file gcc gcc-c++ gettext-devel glibc-static gmp-devel gnutls-devel libargon2-devel libstdc++-static libtool make meson nettle-devel ninja-build patch pugixml-devel sqlite-devel wxGTK-devel xdg-utils

ADD https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage /opt/appimagetool-x86_64.AppImage
RUN chmod +x /opt/appimagetool-x86_64.AppImage

ENV CFLAGS="-O3 -march=native -Wno-error -flto -static"
ENV CXXFLAGS="-O3 -march=native -Wno-error -flto -static"
ENV LDFLAGS="-flto -static"
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
WORKDIR /opt

ADD ./libfilezilla /opt/libfilezilla
RUN \
	cd libfilezilla && \
	autoreconf -f -i && \
	./configure && \
	make -j$(nproc) && \
	make install

ADD ./fzssh /opt/fzssh
RUN \
	cd fzssh && \
	sed -i 's/shared_library(/library(/g' meson.build && \
	sed -i '/^executable(/,/^)$/d' meson.build && \
	sed -i "/^subdir('tests')/d" meson.build && \
	meson setup --libdir=lib --default-library=static build && \
	cd build && \
	meson install

ADD ./filezilla /opt/filezilla
ADD ./transfer-limits.patch /opt/transfer-limits.patch
RUN \
	patch -p1 < /opt/transfer-limits.patch && \
	cd filezilla && \
	mkdir -p ./src/fzshellext/32 ./src/fzshellext/64 && \
	autoreconf -f -i && \
	./configure --with-pugixml=builtin --enable-static --disable-shared && \
	make -j$(nproc) && \
	make install

ADD ./AppRun.sh /opt/approot/AppRun
RUN \
	mkdir -p /opt/approot/opt/filezilla && \
	cp /usr/local/bin/filezilla /opt/approot/opt/filezilla && \
	cp /opt/filezilla/data/filezilla.desktop /opt/approot/filezilla.desktop && \
	cp /opt/filezilla/src/interface/resources/480x480/filezilla.png /opt/approot/filezilla.png && \
	cp -r /usr/local/share/filezilla /opt/approot/opt/filezilla/share && \
	cp -P /usr/local/lib/libf* /opt/approot/opt/filezilla && \
	cp -P /lib64/libcrypt.so* /opt/approot/opt/filezilla && \
	cp -P /lib64/libpugixml.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib64/libwx_*.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib64/libjpeg.so* /opt/approot/opt/filezilla && \
	cp -P /usr/lib64/libmspack.so* /opt/approot/opt/filezilla && \
	strip -s /opt/approot/opt/filezilla/filezilla && \
	strip -s /opt/approot/opt/filezilla/*.so* && \
	chmod +x /opt/approot/AppRun

ENTRYPOINT ["/opt/appimagetool-x86_64.AppImage", "--comp", "zstd", "/opt/approot", "/opt/FileZilla.AppImage"]
